"""Copy the codec-INDEPENDENT conditioning stores into a per-codec data subdir.

Re-tokenizing the corpus to a different codec invalidates only the token-domain
artifacts: the packed shards, the chroma sidecars, and ``keys.json`` (derived from
the packed chroma, hence frame-rate specific). Everything else was derived from the
RAW AUDIO and is reusable verbatim:

    tags.json / tags/   audio-LLM captions   (Qwen2-Audio, A100 — the big spend)
    lyrics/             Whisper transcripts  (+ filter + forced alignment)
    phonemes/           g2p over lyrics/
    structure/          allin1 sections, stored in SECONDS (structure.py:102)
    tempo.json          per-song bpm

Training resolves every one of these under ``/tokens/<data_subdir>``
(``modal_train.py:301``), and a MISSING store degrades **silently** to "no
conditioning" (``dataset.py:33-37`` returns ``{}``) — a run can reach 40k steps
with no lyric conditioning and never warn. So these must be physically present
under the new root before training starts.

Copy rather than symlink or a read-side root fallback: it keeps the train path
untouched, and it lets the two corpora diverge later (e.g. a lyric re-filter for
one codec) without cross-contaminating the other. Cost is ~1k inodes and a few GB.

Run::

    modal run diskrot/modal_copy_conditioning.py --data-subdir dac          # dry run
    modal run diskrot/modal_copy_conditioning.py --data-subdir dac --apply
"""
from __future__ import annotations

import modal

app = modal.App("nano-copy-conditioning")

image = (
    modal.Image.debian_slim(python_version="3.12")
    .add_local_python_source("diskrot")
)

tokens_vol = modal.Volume.from_name("nano-tokens", create_if_missing=True)

# (name, is_dir). keys.json is deliberately ABSENT — it derives from the packed
# chroma, so it is frame-rate specific and must be regenerated by key_detect
# against the new pack, not copied.
STORES: list[tuple[str, bool]] = [
    ("tags.json", False),
    ("tempo.json", False),
    ("tags", True),
    ("lyrics", True),
    ("phonemes", True),
    ("structure", True),
]


@app.function(image=image, volumes={"/tokens": tokens_vol}, timeout=60 * 60 * 4)
def copy_conditioning(data_subdir: str, apply: bool = False) -> dict:
    import shutil
    from pathlib import Path

    if not data_subdir:
        raise SystemExit("--data-subdir is required (e.g. --data-subdir dac)")

    src_root = Path("/tokens")
    dst_root = src_root / data_subdir
    if dst_root.resolve() == src_root.resolve():
        raise SystemExit("--data-subdir must not resolve to /tokens itself")

    report: dict[str, str] = {}
    for name, is_dir in STORES:
        src, dst = src_root / name, dst_root / name
        if not src.exists():
            report[name] = "absent at source — skipped"
            continue
        n = sum(1 for _ in src.rglob("*") if _.is_file()) if is_dir else 1
        if dst.exists():
            report[name] = f"already present at destination ({n} src files) — skipped"
            continue
        report[name] = f"{'COPY' if apply else 'would copy'} {n} file(s)"
        if apply:
            dst.parent.mkdir(parents=True, exist_ok=True)
            if is_dir:
                shutil.copytree(src, dst)
            else:
                shutil.copy2(src, dst)

    for name, line in report.items():
        print(f"  {name:12s} {line}", flush=True)
    if apply:
        tokens_vol.commit()
        print(f"\ncommitted -> {dst_root}", flush=True)
        # Post-copy assert: a partial copy is the failure mode that would train
        # silently-unconditioned, so verify presence rather than trusting the loop.
        missing = [n for n, _ in STORES
                   if (src_root / n).exists() and not (dst_root / n).exists()]
        if missing:
            raise SystemExit(f"VERIFY FAILED — missing under {dst_root}: {missing}")
        print("verify: every source store is present at the destination", flush=True)
    else:
        print("\nDRY RUN — pass --apply to copy", flush=True)
    print("NOTE: keys.json is intentionally NOT copied — it derives from the packed "
          "chroma and must be regenerated:\n"
          f"  modal run diskrot/modal_key_detect.py --data-subdir {data_subdir}",
          flush=True)
    return report


@app.local_entrypoint()
def main(data_subdir: str = "", apply: bool = False):
    copy_conditioning.remote(data_subdir=data_subdir, apply=apply)
